/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Libro.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Libro.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001" scale={0.118}>
          <primitive object={nodes.ROOT_ROTATION} />
          <primitive object={nodes.ROTATION_MID01} />
          <primitive object={nodes.ROTATION_BOT} />
          <skinnedMesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.001']} skeleton={nodes.Plane002.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Libro.gltf')
